import {Epilogue} from "next/font/google";
import "../globals.css";
import { Metadata } from "next";

const epilogue = Epilogue({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Sign in",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={epilogue.className}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
