import { Metadata } from "next";
import React, {FC} from "react";

interface SignUpPageProps{

}

export const metadata: Metadata = {
  title: "Sign up",
  description: "Generated by create next app",
};

const SignUpPage: FC<SignUpPageProps> = ({})=>{
  return(
    <div>
      SignUpPage
    </div>
  );
}

export default SignUpPage;